# =========================================
# NOMBRE DE LA APLICACION
# =========================================
spring.application.name=FreakyWorld

# =========================================
# PUERTO
# =========================================
server.port=90

# =========================================
# CONEXION A MYSQL
# =========================================
spring.datasource.url=jdbc:mysql://localhost:3306/freakyworld?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# =========================================
# THYMELEAF
# =========================================
spring.thymeleaf.cache=false

# =========================================
# ARCHIVOS
# =========================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================================
# FIREBASE
# =========================================
firebase.bucket-name=freakyworld-677da.firebasestorage.app
firebase.storage.path=freakyworld
firebase.json.path=firebase
firebase.json.file=freakyworld-677da-firebase-adminsdk-fbsvc-53719cbceb.json
